### ISSUE TITLE
Wrong condition

### ISSUE THREAD

**Issue by NdK73** [ergo70/atecc608a#2]
https://github.com/ergo70/atecc608a/blob/a6663faa8936c2cd8d44293e1860daf654e2e894/atecc608a.py#L176
The check is wrong: it would accept any other datatype as long as its len is 32.
It should be something like:
`if not (type(data) is bytearray and 32 != len(data)):`

**Comment by ergo70** [comment]
I will fix that. Thx for the correction.

**Comment by NdK73** [comment]
Err... Sorry, I just noticed an error in my correction. Better to just change 'and' with 'or' in the original expr, so it raises exception if it's not a bytearray *or* its len is not 32.
IIRC Python (like C) short-circuits expressions, so len will not be checked if data is not a bytearray.
`if (not type(data) is bytearray) or 32 != len(data):`

**Comment by ergo70** [comment]
Thx, I've fixed it per your suggestion.
